# Generated by Django 3.0.5 on 2023-08-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=123, upload_to='gallery'),
            preserve_default=False,
        ),
    ]
